apiVersion: apps/v1
kind: Deployment
metadata:
  name: peekcart
  namespace: peekcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peekcart
  template:
    metadata:
      labels:
        app: peekcart
    spec:
      containers:
        - name: peekcart
          image: ghcr.io/kimgyuilli/peakcart:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: peekcart-config
            - secretRef:
                name: peekcart-secret
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: peekcart
  namespace: peekcart
spec:
  type: NodePort
  selector:
    app: peekcart
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
